services:

  db:
    image: postgres:17-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: s3cr3t!
      PGDATA: /var/lib/postgresql/data/pgdata
      PGTZ: UTC
      TZ: UTC
#    volumes:
#      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
