services:
  api:
    image: openjdk:21
    working_dir: /application
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./api.jar:/application/api.jar:ro
      - ./docker-run.sh:/application/docker-run.sh:ro
    command: [ "/application/docker-run.sh" ]
    restart: always
    ports:
      - "0.0.0.0:8080:8080"
    healthcheck:
      test: curl -s http://127.0.0.1:8080/actuator/health | grep -i up
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
