openapi: 3.0.3
info:
  title: dependencies-json-server API
  description: dependencies-json-server API
  version: v1
servers:
  - url: https://localhost:8080
    description: dev
tags:
  - name: Example
paths:
  /projects/{key}:
    post:
      tags:
        - Project
      description: Add project information to project with given key.
      operationId: processProject
      parameters:
        - name: key
          in: path
          description: Unique project identifier.
          required: true
          style: simple
          explode: false
          schema:
            type: string
          example: my-cool-project
      requestBody:
        description: The project definition.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"
        required: true
      responses:
        "201":
          description: No content
components:
  schemas:
    Dependency:
      required:
        - file
        - group
        - name
        - version
      type: object
      properties:
        group:
          type: string
          example: org.jetbrains.kotlin
        name:
          type: string
          example: kotlin-stdlib
        version:
          type: string
          example: 2.1.20
        file:
          type: string
          example: kotlin-stdlib-2.1.20.jar
    Project:
      required:
        - dependencies
        - group
        - name
        - timestamp
        - version
      type: object
      properties:
        group:
          maxLength: 128
          minLength: 1
          type: string
          example: org.jetbrains.kotlin
        name:
          maxLength: 64
          minLength: 1
          type: string
          example: api
        version:
          maxLength: 32
          minLength: 1
          type: string
          example: 1.0.0-SNAPSHOT
        timestamp:
          type: string
          format: date-time
          example: 2025-04-23T23:32:10.246992Z
        dependencies:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: "#/components/schemas/Dependency"
