openapi: 3.0.3
info:
  title: ignored
  version: ignored

tags:
  - name: Example

paths:
  /projects/{id}:
    post:
      description: Add project information to project with given key.
      tags:
        - Project
      operationId: processProject
      requestBody:
        description: The project definition.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"
      parameters:
        - in: path
          name: id
          description: Unique project identifier.
          required: true
          schema:
            type: string
      responses:
        "201":
          description: No content

components:
  schemas:
    Project:
      type: object
      properties:
        name:
          type: string
          example: "api"
        version:
          type: string
          example: "1.0.0-SNAPSHOT"
        timestamp:
          type: string
          format: date-time
          example: "2025-04-23T23:32:10.246992Z"
        dependencies:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/Dependency'
      required:
        - name
        - version
        - timestamp
        - dependencies

    Dependency:
      type: object
      properties:
        group:
          type: string
          example: "org.jetbrains.kotlin"
        name:
          type: string
          example: "kotlin-stdlib"
        version:
          type: string
          example: "2.1.20"
        file:
          type: string
          example: "kotlin-stdlib-2.1.20.jar"
      required:
        - group
        - name
        - version
        - file